### ISSUE TITLE
Add shows not included in cagematch

### ISSUE THREAD

**Issue by gordonjb** [gordonjb/graplist.fm#12]
Some shows (and promotions) aren't included in Cagematch! 😱

We should have a way to add cards that are missing.

Probably a list of yaml/json files with the info? would need to be linkable to the worker/show info

**Comment by gordonjb** [comment]
Example:

```
show: 
  show_name: "Anarchy Pro Master Of Brutality Tournament: Stage Three"
  promotion: "Anarchy Pro Wrestling"
  date: "10.05.2018"
  arena: "Lock 17"
  location: "London, England, UK"
  partial: true
  exclude_from_count: true
matches: 
  - "Eddie Dennis def. Chief Deputy Dunne"
  - "Charli Evans def. Kid Lykos"
  - "WALTER def. Chris Brookes"
  - "Session Moth Martina def. Roy Johnson"
  - "Drew Parker def. Clint Margera"
```

Probably needs to add ids to matches somehow. Is that easier than an "all workers" equivalent section?
